export { Login } from "./Login";
export { Register } from "./Register";
export { CadastroEstoque } from "./CadastroEstoque";
export { CadastroUsers } from "./CadastroUsers";
export { Perfil } from "./Perfil";
export { Home } from "./Home";
export { CadastroCategoria } from "./CadastroCategoria";
export { CadastroProduto } from "./CadastroProduto";
export { CadastroFornecedor} from "./CadastroFornecedor";
export { CadastroLote } from "./CadastroLote";